config/routes.rb
Rails.application.routes.draw do
  get 'index/index'
  
 root to: "index#index"
  resources :users

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  resources :books

  get '/books', to: 'books#index'
  post '/book', to: 'books#create'

  resources :books do
    post 'borrow', to: 'borrows#create', on: :member
  end

  resources :books do
    patch 'return_book', to: 'borrows#return_book', on: :member
  end

  resources :borrows do
    patch 'lose', to: 'borrows#lose_book', on: :member
  end

  resources :books do
    member do 
      get 'admin_access'
    end
  end

  resources :users do
    member do 
      get 'borrowed_book'
    end
  end

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/search', to: 'books#search', as: 'search_books'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book.rb
class Book < ApplicationRecord

    has_many :borrows
    has_many :users, through: :borrows

    validates :name, presence: true
    validates :image_url, presence: true
    validates :author, presence: true
    validates :description, presence: true
    validates :year_of_release, presence: true, numericality: { only_integer: true }
    validates :category, presence: true
    validates :available_book_count, presence: true, numericality: { only_integer: true }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:edit, :update, :destroy]
    
    def new
        @book = Book.new
    end 

    def admin_access
      @books = Book.all
      @books_with_borrowers = Book.includes(:borrows, :users).all

      # SELECT books.*, borrows.*, users.*
      # FROM books
      # LEFT JOIN borrows ON borrows.book_id = books.id
      # LEFT JOIN users ON users.id = borrows.user_id

    end

    def index

      if params[:query].present?
        @books = Book.search(params[:query]).records
      elsif params[:category].present?
       @books = Book.where(category: params[:category])  
      else
        @books = Book.all
      end
      
        

      
    end
    

    def create
        @book = Book.new(book_params)
        if @book.save
            redirect_to books_path, notice: "book added success fuly"
        else
            render :new
        end
    end

    def edit
    end

    def show
        @book = Book.find(params[:id])
    end

    
    def update
        if @book.update(book_params)   
          redirect_to books_path, notice: 'Book was successfully updated.'
        else
          render :edit
        end
      end
    
      def destroy
        @book.destroy
        redirect_to new_book_path, notice: 'Book was successfully deleted.'
      end

      def search
        @books = Book.all
        if params[:category].present?
          @books = @books.where(category: params[:category])
        end
        render json: @books  
      end
      

    private

    def set_book
        @book = Book.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = 'Book not found.'
        redirect_to books_path
      end
    
    def book_params
       params.require(:book).permit(:name, :image_url, :author, :description, :year_of_release, :category, :available_book_count)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= stylesheet_link_tag 'form' %>

<%= form_for(@book) do |f| %>

  <h2>Edit Book</h2>
    
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  
    <div>
      <%= f.label :image_url %>
      <%= f.text_field :image_url %>
    </div>
  
    <div>
      <%= f.label :author %>
      <%= f.text_field :author %>
    </div>
  
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
  
    <div>
      <%= f.label :year_of_release %>
      <%= f.number_field :year_of_release %>
    </div>
  
    <div>
      <%= f.label :category %>
      <%= f.text_field :category %>
    </div>

    <div>
      <%= f.label :available_book_count%>
      <%= f.number_field :available_book_count %>
    </div>
  
    <div>
      <%= f.submit 'Update Book' %>
    </div>
    <%= link_to 'Back', books_path %>
  <% end %>
  

app/views/books/admin_access.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>Books Admin Page</h1>
  <%= link_to 'New Book', new_book_path, class: 'btn btn-success' %>
</div>

<% if @books.count >= 1 %>
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Book</th>
        <th>Author</th>
        <th>Book count</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.name %></td>
          <td><%= book.author %></td>
          <td><%= book.available_book_count %></td>
          <td>
            <%= link_to 'Edit', edit_book_path(id: book.id), class: 'btn btn-primary btn-sm' %>
            
          </td>
          <td>
          <%= button_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
          <td>
            <%= link_to 'show', book_path(id: book.id), class: 'card_link' %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No books added yet.</p>
<% end %>

<h3>users details</h3>


<% if @books_with_borrowers.count >= 1 %>
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>id</th>
        <th>User</th>
        <th>Book</th>
        <th>Status</th>
        <th>Borrow Count</th>
      </tr>
    </thead>
    <tbody>
      <% @books_with_borrowers.each do |book| %>
        <% book.borrows.each do |borrow| %>
          <tr>
            <td><%=borrow.id%></td>

            <td>user id : <%= borrow.user.id%> name:  <%= borrow.user.username %></td>
            <td><%= book.name %></td>
            <td>
              <% if borrow.returned_date.present? %>
                Returned
              <% elsif borrow.lose_book.present? %>
                Lost
              <% else %>
                Borrowed
              <% end %>
            </td>
            <td><%= borrow.user.borrow_count %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No books added yet.</p>
<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<%= stylesheet_link_tag 'book' %>
<%= stylesheet_link_tag 'filter_form' %>


<%= form_tag(books_path, method: :get, class: 'filter-form') do %>
  <%= select_tag(:category, options_for_select(['', 'Fiction', 'history', 'bio_graphical'])) %>
  <%= submit_tag('Filter') %>
<% end %>



<div class="body">

<% @books.each do |book| %>
  <div id="obsu" style="margin-top: 100px;">
  <div id="sekil">
    <img src="<%= book.image_url %>" alt="" />
  </div>
  <div id="kitabadi">
    <h2><%= book.name %></h2>
  </div>
  <div id="kimindi">
    <p>by <%= book.author %></p>
  </div>  

  <div id="haqqinda">
    <p><%= book.description %></p>
  </div>
  <div id="qiymet">

  <% if book.available_book_count >= 1 %>
  <%= form_for Borrow.new, url: borrow_book_path(id: book.id), method: :post do |f| %>
    <%= f.hidden_field :return_book, value: false %>
    <%= f.hidden_field :borrow_date, value: Date.today %>
    <%= f.hidden_field :return_date, value: (Date.today + 10).to_s %>
    <%= f.hidden_field :returned_date, value: nil %>
    <%= f.submit "Borrow", class: "btn btn-primary" %>
  <% end %>
<% else %>
  <button type="button" class="btn btn-danger">Not Available</button>
<% end %>

  </div>
</div>

<% end %>


</div>

app/views/books/new.html.erb
<%= stylesheet_link_tag 'form' %>



<%= form_for(@book) do |f| %>
   <h4>New Book</h4>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :year_of_release %>
    <%= f.number_field :year_of_release %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div>
    <%= f.label :available_book_count %>
    <%= f.number_field :available_book_count %>
  </div>


  <div>
    <%= f.submit 'Create Book' %> 
  </div>
  <%= link_to 'Back', books_path %>
<% end %>

app/views/books/search.html.erb
<h1>Search Results</h1>

<% if @results.any? %>
  <ul>
    <% @results.each do |book| %>
      <li><%= link_to book.name, book_path(book) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/books/show.html.erb
<%= stylesheet_link_tag 'book_show' %>
<div class="container mt-4 content-container connn">
  <div class="row">
    <div class="col-md-6">
      <img src = "<%= @book.image_url %>" class="image img-fluid rounded">
    </div>

    <div class="col-md-6 d-flex align-items-center justify-content-space-around con1">
      <div>
        <h2><%= @book.name %></h2>
        <br>
        <p><strong>Author:</strong> <%= @book.author %></p>
        <br>
        <p><strong>Year of Release:</strong> <%= @book.year_of_release %></p>
        <br>
        <p><strong>Category:</strong> <%= @book.category %></p>
        <br>
        <p><strong>Available Book Count:</strong> <%= @book.available_book_count %></p>
        <br>

        <h4>Description:</h4>
        <p><%= @book.description %></p>
      </div>
    </div>
  </div>
</div>